In [14]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import pickle
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [6]:
df = pd.read_csv("House_price.csv")

df.head(5)

,Avg. Area Income,House Age,Number of Rooms,Number of Bedrooms,Area Population,Price,Address
0,79545.45857,5.682861,7.009188,4.09,23086.80050,1.059034e+06,"208 Michael Ferry Apt. 674\nLaurabury, NE 3701..."
1,79248.64245,6.002900,6.730821,3.09,40173.07217,1.505891e+06,"188 Johnson Views Suite 079\nLake Kathleen, CA..."
2,61287.06718,5.865890,8.512727,5.13,36882.15940,1.058988e+06,"9127 Elizabeth Stravenue\nDanieltown, WI 06482..."
3,63345.24005,7.188236,5.586729,3.26,34310.24283,1.260617e+06,USS Barnett\nFPO AP 44820
4,59982.19723,5.040555,7.839388,4.23,26354.10947,6.309435e+05,USNS Raymond\nFPO AE 09386

In [8]:
df.shape

(4548, 7)

In [9]:
df.isnull().sum()

Avg. Area Income      0
House Age             0
Number of Rooms       0
Number of Bedrooms    0
Area Population       0
Price                 0
Address               0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.drop(columns='Address', inplace=True)

In [13]:
X = df[["Avg. Area Income", "House Age", "Number of Rooms", "Number of Bedrooms", "Area Population"]]
y = df["Price"]

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [16]:
lr = LinearRegression()

In [17]:
lr.fit(X_train, y_train)

LinearRegression()

In [18]:
y_pred = lr.predict(X_test)

In [19]:
y_pred

array([1249025.31928701,  465751.14449644,  997391.65223635,
       1344602.75755151, 1427909.48796315, 1073470.19949207,
       1166795.97488747, 1347491.54676713, 1218452.11490942,
        954265.5134281 , 1384270.14876339, 1385606.57568144,
       1233771.60051843, 1051258.71909163, 1784970.91409964,
        538700.79153853, 1828268.53243087, 1540602.14283523,
       1489423.0630629 , 1446227.34821622, 1115208.2950502 ,
       1087621.26355176,  935173.1514318 , 1203244.63739194,
       1159410.10842438, 1047280.68615225, 1497079.97896401,
       1374164.97311043,  841342.83569503, 1196000.45142825,
        693876.23277837, 1465788.67414709, 1258211.01261991,
       1173756.91694465,  914148.62213266,  613408.16116547,
       1584231.76488834,  909183.77008053,  764065.31897927,
        869781.64586819,  428190.13655176, 1169124.72467137,
       1375722.48194505, 1425597.42011708, 1076381.93746125,
        872238.53815836,  961550.11536178, 1562472.92930783,
        952082.84106276, 1316321.85087856, 1475917.07296948,
       1189661.29361356, 1738293.9247111 , 1221178.9018429 ,
       1191083.45619858, 1131188.18917002,  858868.81699672,
       1528025.39891993, 1223836.81711621, 1029827.45197802,
       1497232.28356064, 1065607.66350031, 1075156.53689531,
       1061581.23118255, 1361365.93184488, 1787319.31008132,
       1761045.78051208, 1254390.95539394, 1425670.61762145,
        994390.33148794, 1529451.19202281, 1649383.39039741,
       1270236.87294861, 1636442.91200879, 1158972.61025084,
       1373281.05885054, 1320571.31250499,  967366.24623519,
       1518630.36837266, 1288280.85664982, 1192275.33984921,
        976844.63357645, 1254900.17902821,  858892.2359159 ,
       1180861.30492133, 1213832.59380282, 1436727.6302014 ,
       1279518.44136262, 1184603.26992102, 1226632.50976916,
       1588317.53094752, 1266212.11470387, 1272796.65789777,
       1206578.75153967, 1119299.01551496, 1022861.92423989,
       1502438.56692166, 1370616.45277107, 1738056.22161251,
       1439539.04668654, 1476919.52447059, 1348720.28767864,
       1362438.5338417 ,  624293.88506864, 1128297.49792018,
       1537360.37092118, 1673858.58908094, 1264158.87711558,
       1038498.29858028, 1597103.78930973, 1407171.6401648 ,
        970554.78807117, 1194699.72410922, 1068043.36463614,
       2056176.62901716,  782902.15920974, 1307456.84882621,
       1101196.48594106,  931109.11908535, 1352876.51788692,
       1148248.61824596,  932808.78824494, 1182783.11367011,
        746151.78472798, 1235158.71445935, 1226920.1157077 ,
       1223965.88920645, 1152538.7813408 ,  574635.12733911,
       1182859.66625565,  484699.1891619 , 1367790.32199568,
       1204591.80793308, 1567134.06080252, 1189298.37522552,
       1057698.94590789, 1186894.99835149,  966611.52306062,
       1193580.90433753, 1117846.71913594, 1827735.51413488,
       1822880.27582244, 1608357.20212499,  974069.81646447,
       1274008.24098749, 1017050.71732596, 1532890.23140113,
       1174760.9911971 , 1482866.94170983, 1646907.52793161,
       1353803.12849687, 1449564.31440015,  689121.29585349,
       1009078.37841362, 1581071.65932562, 1289263.74462827,
        847884.98158656, 1299602.68719339, 1778888.52928063,
       1036174.65781659, 1757347.25890585, 1167844.13381516,
       1119306.39196206, 1794268.59054105, 1348522.98740738,
       1350528.00500409, 1120889.44156313,  669352.46985616,
       1574392.04149592,  957981.7770872 , 1568108.75383607,
       1179660.7406427 , 1353488.63782435, 1258340.71676092,
       1471187.82508217, 1193221.13285469,  473678.29891147,
       1122447.47919261, 1032340.22296112, 1489885.27666906,
       1102764.82619249, 1511428.66261224,  852877.50434657,
       1617671.76214233, 1693918.26525183, 1410237.14820122,
        845010.91937063, 1913473.33613764, 1348342.03733281,
        787385.06364504, 1348240.82429938, 1052259.78550896,
       1383857.28182874,  776763.94079419, 1526005.19269497,
       1227672.97096313,  925180.70578619, 1294575.88443134,
        511455.00724505, 1340133.60777988, 1488497.10270248,
        814412.39571033, 1328843.70384302, 1373313.51346253,
       1335169.26180899, 1087654.13409961, 1235222.70126854,
       1257633.64634833, 1731892.36535369, 1746976.10467025,
       1120076.44592108, 1405063.45937665,  990527.31742531,
       1336929.78730394, 1339791.50766574, 1138626.88800595,
       1309249.14288009, 1432907.55343186, 1500673.5631488 ,
       1690652.45669954, 1487206.71640961, 1196870.25866846,
       1612114.30660821, 1195475.41793258,  591994.14770163,
       1694523.75226116,  776666.32878781, 1250901.58094791,
       1010794.80392094, 1610151.73881625,  924397.89647526,
        900167.72919326, 1550208.12318075, 1282803.75070735,
       1857384.11051755, 1278695.73619387,  856170.06743321,
       1115105.97574089, 1111837.48266335, 1511670.18127461,
        924822.19150354, 2471917.39642323, 1490916.20392824,
       1637290.26041112,  708736.98533731, 1504634.69214416,
       2001283.30824274, 1480451.07468503, 2251329.55071575,
       1292787.43790887,  711657.68733468, 1327951.52226103,
        488462.28739294, 1690394.35622425,  771669.30229525,
        974291.52499231, 1128714.83400173,  577394.28754721,
       1728777.97388007,  716138.20970666,  768578.91365117,
        768261.25743636, 1751769.55519747,  911367.7635445 ,
        643429.94276412, 1662521.59086023,  897038.45186263,
       1665120.79837092, 1301210.66799613, 1171669.71282122,
        569106.51868061, 1049906.79863262,  640088.29662195,
       1421138.81505508, 1439358.19728051,  999422.14820741,
       1521075.76196618, 1397476.0534211 , 1285235.59832882,
       1573290.91144613, 1008910.76314158, 1290740.59042961,
        999319.72996317, 1034748.90309574, 1357817.19997715,
        974286.40868689, 1572970.57678872, 1127345.72566206,
        937871.05175799, 1136671.6333916 , 1187743.94041849,
       1481509.39943293,  958865.637017  , 1284765.53958569,
       1070907.67806729, 1407979.61335939, 1620598.62004784,
        928443.31849607, 1145239.36313442,  871935.41315787,
        518937.97755752, 1048365.34904769, 1411198.11473259,
       1637526.24936193, 1022909.48955607,  966738.96408502,
       1409256.19432248, 1247757.67552776, 1264935.19866025,
       1078547.46996207, 1309622.21593315,  803458.11328546,
       1187250.22169647, 1284391.78000124, 1255003.26407294,
       1486022.37948487, 1421518.32284435, 1056326.09075087,
       1601352.55775299, 1122777.81892526, 1443444.89556037,
       1526508.20072838,  584220.51398497, 1029670.49523841,
       1457476.85792952, 1046236.80815177, 1088136.29882754,
       1083774.88755919, 2117221.79241789, 1466887.2727056 ,
       1024853.04761464, 1308250.36042151,  777826.06994426,
       1067370.57969262, 1200274.9702647 , 1380432.39280366,
       1502926.87187287, 1171381.45254156,  848728.43522281,
       1497100.93707864,  695199.32486419,  433798.55097198,
       1654750.30961197, 1222552.16008316, 1573081.67652095,
       1433948.32857284, 1308130.26129166, 1059869.3869816 ,
       1113743.39302721, 1648130.24136382, 1600270.43606219,
        987049.12786201, 1092828.4635137 ,  898728.83265251,
       1902501.00723364, 1423314.49697561, 1543269.80883135,
        766880.54290465, 1266243.06098876, 1124154.65309037,
       1221532.58675006, 1189962.6544647 , 1204557.98236344,
       1610519.65776457, 1200672.8786617 , 1317795.15068209,
       1335389.04641533, 1170196.99241329, 1703507.20970281,
       1361428.78781755, 1298248.56828897, 1343033.19758035,
       1216971.03402263, 1188491.12755097, 1261956.04979427,
       2337878.92327998, 1692925.98701039, 1575138.18382461,
       1087460.03195568,  712144.21305313,  603681.88666565,
       1048975.83589542, 1519823.45172199, 1067747.79107635,
       1394291.51268908, 1663817.41161991,  710190.7322563 ,
        695767.44718896, 1308515.03816233, 1742432.21489475,
       1035475.56908422, 1100194.0337892 ,  843375.02841998,
       1412125.66020483, 1107410.71991072, 1125498.47691257,
       1200261.29920359, 1769463.38042477,  750447.96784478,
       1199505.46778792, 1020848.89919996,  971089.52906232,
       1278348.15274041, 1109200.11815009, 1314972.80825337,
        446302.68859372,  968922.96147448, 1256110.84159863,
        993891.06338425, 1708437.5180734 ,  952490.4773997 ,
       1563249.82559886,  872047.2704181 ,  666320.63337637,
       1302773.60171338, 1580146.49374506, 1654837.14799885,
       1594855.45157822,  908535.42486471, 1051185.23131543,
       1992172.52356249, 1360005.49485182,  776900.47506608,
        972671.35233879, 1634624.82053123, 1404970.06308123,
       1017634.675112  , 1536245.06428596,  769905.67160304,
       1404159.47865926, 1390567.05532468,  742112.47798093,
       1473537.26014825,  872878.06643569, 1696822.46860223,
       1461995.53656247,  960417.84022571, 1424985.87692407,
        884997.92814014,  851381.07518327, 1541552.70020907,
       1290022.12952814, 1312764.7926869 , 1383293.7395425 ,
        996868.61574129, 1043259.28103355, 1168494.06885927,
       1110468.02036889,  992464.67101229, 1334405.22165769,
        893194.50090688, 1357543.85928032,  908631.020178  ,
        793064.39572634, 1503332.00240926, 1249801.73216962,
        421621.02095696, 1134795.62596542, 1398970.36972099,
       1394906.50907381, 1509313.08332368, 1750132.30962716,
       1128267.24060899, 1785655.92289387, 1311790.47999401,
       1121005.75555689, 1453604.88062195, 1156830.1626989 ,
       1672959.56182531, 1470465.74471137, 1462104.8283582 ,
       1171120.67341905, 1266345.69169016, 1209308.67426235,
       1305069.74676653, 1243716.14272918, 1633839.35467043,
       1378879.14426392,  669195.60677712,  913669.08362102,
       1690535.26686407, 1749772.93013811, 1039069.94200906,
       1706460.24859112, 1823017.03132153, 1236681.57202457,
       1301017.62596711,  875436.05567885, 1977392.72166468,
        656340.11056138, 1044176.79509615, 1153210.41816396,
       1512736.56346456,  771084.131811  , 1424513.47479388,
        629069.85373122, 1435224.9624149 , 1403075.72454995,
       2165404.67251095, 1354070.79694478, 1237481.83980112,
        679642.94142528, 1064205.33067041,  968156.17374715,
       1322582.35629538, 1570251.16745383, 1157121.24191326,
       1285439.69966032, 1048050.58850274, 1710717.92914667,
       1405492.47860091,  833696.13291885,  499448.85935776,
       1727269.36513048, 1795339.14327368,  857346.40767809,
        722432.71605518,  622616.95136287, 1423482.1357658 ,
       1131750.35220257, 1449929.65104231, 1095875.56114069,
        458432.24867821, 1125796.10372217, 1290127.60788176,
        780252.74323168, 1285775.33892729, 1709627.11368549,
        714640.1091743 , 1602205.25311437, 1029987.92716131,
       1303921.67994682,  844136.26521302, 1552687.2890408 ,
       1374434.08677025,  879334.11580629, 1124690.73409669,
       1118899.76392234, 1440896.86966116, 1439839.68806764,
       1595538.71017791,  529120.66633348, 1457406.16927384,
       1656635.51499971, 1002620.26440352, 1399091.97440776,
       1030837.69849587,  909885.84836128, 1215154.38282357,
       1032406.46117825, 1810776.76389873, 1230520.71189369,
       1353971.80664171, 1710819.56473673, 1102000.22158905,
       1296044.13821165, 1326030.59334807, 1628100.71700299,
       1296276.69242082, 1060577.12130891, 1392553.35216329,
       1074447.47032001, 1624963.44419826, 1762479.48023385,
        395255.49133792, 1290365.08470001, 1039011.3238308 ,
       1239380.71387994, 1354452.20565247,  827333.02492694,
       1186671.26512908, 1421061.48313667, 1051579.3481369 ,
       1355690.99367399, 1462279.14028902, 1526167.89979718,
       1090770.81810233, 1234499.58252738,  776226.36732465,
       1282755.2677044 , 1674015.06236567, 1683827.10765117,
       1612477.81951473, 1638973.66639623, 1088853.16716623,
       1182303.38462725, 1332455.68768596, 1823647.59113108,
       1493361.22907321, 1056373.65807835, 1142743.65657549,
       1363526.01931664, 1330518.71147091, 1803499.42725054,
       1075129.37401381, 1156146.89422644,  774823.32666035,
        462029.6017486 , 1692387.58171863, 1316757.84960097,
       1564672.32270018,  872617.6745775 ,  738498.76840475,
       1507401.43907314, 1053839.79150074, 1462785.01967696,
        738681.34268578,  838669.60443898, 1484223.35967066,
       1069703.41617408,  736644.68484085,  732022.11621295,
        987808.06533391, 1491179.67513074, 1420177.08349121,
       1100679.18052309, 1027019.13414664, 1291484.45027966,
       1060417.6408632 , 1566170.86259901, 1518218.69863493,
        649778.27329104, 1795358.5481791 , 1429815.10852526,
       1645748.68294987, 1679635.04452435, 1395817.91707397,
       1186922.9144625 , 1451857.53729006, 1206061.69989289,
       1602509.44315271, 1512751.83581939, 1175024.4171772 ,
       1113281.55965328, 1479278.8469421 ,  922780.9336692 ,
       1436773.56177377, 1127546.24384995,  970318.80481259,
       1721523.42584966, 1771349.80917721, 1612482.65081281,
       1028574.42749636, 1542576.66569988, 1523404.9599975 ,
       1180057.85381854, 1203956.70068462, 1764062.85183553,
        947793.82370319, 1093959.59176512,  832239.30992022,
        861962.26497295,  883494.02415205, 1211686.53197973,
       1307362.87869396, 1034335.71086062, 1385436.03582615,
       1526049.32277755, 1568884.1309974 ,  886353.86769614,
       1005583.20029806, 1365211.69810586, 1351570.56142196,
       1323553.21966194, 1342501.76702623, 1407763.38371474,
        726890.89119235, 1188026.22544444, 1615622.24762544,
       1412975.21751782, 1043443.4488602 ,  911256.58297395,
       1464381.10509826,  781010.46500166,  787685.63311545,
       1455411.7587026 , 1481722.69319735, 1234792.37394166,
        672154.13918266,  843210.73963171, 1312109.94588386,
       1550871.94329533, 1271315.08373864, 1409266.30149095,
       1500079.49070307, 1439135.0643553 , 1077787.55849391,
        790444.37083917, 1191727.62522211, 1843231.45598944,
       1638700.68240518,  961780.63998007, 1499727.55438264,
       1246537.54970418, 1137502.76549652, 1122012.36934991,
        828241.98239611, 1141620.18724818, 1246196.19880517,
       1861229.33669922,  980977.22022458, 1126873.89315863,
       1547061.25499699, 1726215.13788874, 1084528.65205785,
       1076993.99421713, 1443361.26167471, 1760089.26161787,
       1557762.2997947 , 1118942.81046476, 1280284.68859747,
       1219217.36800444, 1277349.26460749,  831300.86850365,
       1800188.49140691, 1238401.51458219, 1491465.56592495,
       1312365.55986307, 1145761.84526792, 1855433.64405681,
       1270766.89209204, 1513623.65965475, 1171263.84487996,
        857003.14409696, 1090105.38296476, 1145048.45487378,
       1246583.06987211, 1046427.56770647,  794102.29268755,
        842901.69809596, 1274222.45047729, 1623335.51454522,
       1550730.19166378,  911997.5809923 , 1176093.6487252 ,
       1059519.41282535, 1260272.94559909, 1368527.12187744,
       1702173.93139424, 1052037.93103231, 1718556.46730682,
       1212997.59663412, 1736316.69674253, 1249477.44774924,
       1463063.98672281, 1280402.65403214, 1274768.30871708,
       1143073.65405134, 1896796.20500705, 1063110.92122528,
       1652205.06509339, 1416015.87892457, 1660161.39321403,
       1791044.00061105,  859347.45982119,  691481.29308306,
       1324579.09501557, 1379920.54615591, 1114939.58962314,
        945422.59467959, 1547924.19627284, 1533979.0074516 ,
        688224.24301911, 1439942.55483196, 1309545.50672839,
       1097456.95440671, 1075934.73280088, 1450917.2453998 ,
       1078269.8229409 , 1369435.5813927 ,  575297.59907564,
       1134648.93876491, 1643552.4975713 , 1079505.26053954,
       1204410.08993434, 1005940.61665858, 1181585.30380788,
       1620161.08646341, 1305654.76187502, 1213110.4925259 ,
       1457188.72142751, 1415534.93291571, 1364045.54471833,
       1546776.32970062, 1015978.96117272, 1189505.93810247,
       1090496.93674939,  830577.01463741,  886214.6768882 ,
       1304675.39777777,  768389.27327866, 1494622.50907148,
       1510020.25750408, 1595153.07675549, 1534571.35674549,
        993783.4343433 , 1030719.85305033, 1306603.65380467,
       1424183.77323183, 1328687.80346726,  695485.68432699,
        610089.23639038,  999293.73415275, 1375408.12794647,
       1055058.94724061, 1100525.12602342, 1366818.50473507,
       1034827.25889167, 1458937.78416749,  842292.75061704,
       1431058.2832253 , 1188902.32361555,  980233.77601665,
       1620285.65533116, 1485618.92967044, 1191735.82047278,
       1688911.02502781, 1288498.42022413, 1393278.08000914,
        949022.90362414, 1086825.14152145,  915209.69812728,
       1456338.12625965, 1191964.3795947 ,  986423.33557279,
       1119231.62122967, 1040104.37040023, 1254481.44203015,
        982588.77718926, 1479424.48055934, 1457853.77309151,
       1158457.01974505, 1513533.14740295, 1284548.03684547,
       1394542.43883741, 1239272.14974961, 1255946.13729026,
        939925.04336897, 1406553.58419528, 1326495.23052463,
       1284046.17026719, 1119547.11997767, 1849154.46623363,
       1208236.01380946, 1329210.42389651, 1348027.49522967,
       1160200.77370882, 1801541.50206189,  879546.01743793,
       1097165.05089377, 1785151.37170424, 1303303.29829084,
       1522285.89597857, 2198310.08096913,  915734.7286395 ,
        914718.26538709,  968991.22964744,  978973.35756504,
       1575908.10241425, 1514186.98958471, 1086611.04054559,
       1359630.27770481, 1401253.74113942, 1666757.99060317,
       1378002.08158247, 1025471.74248517, 1322808.97700183,
        932397.90289979, 1058539.34800004, 1107773.0049459 ,
       1842997.84206328, 1100587.2346737 , 1217638.19002669,
       1155623.59231784, 1581370.42937271, 1236437.44249911,
       1303332.743142  , 1235364.7557516 , 1032212.03760421,
       1113063.0659411 , 1395224.34546683, 1168482.20629054,
        774740.77276476,  651347.18560401,  547022.31123229,
       1171090.29601388, 1142097.59294242, 1588044.18206066,
       1685444.10251911, 1396713.25727812, 1599105.4784183 ,
       1401379.63424769, 1801743.98474979, 1564175.22661775,
        826545.61581224, 1296294.19716039, 1293119.31431719,
       1498470.35033272, 1685899.78786534,  939807.53881285,
       1327705.84083274, 1651648.96434255, 1938038.01274208,
       1672928.6595632 , 1368962.08644894, 1113896.58709596,
        777471.22333469, 1344279.7868036 , 1717552.23413999,
       1469172.05093549])

In [20]:
X_test

,Avg. Area Income,House Age,Number of Rooms,Number of Bedrooms,Area Population
471,62134.02206,7.445436,6.808879,2.20,32157.13169
2517,50847.11311,4.973274,5.355861,4.38,34763.70381
23,60697.35154,6.170484,7.150537,6.34,28140.96709
3918,63700.88828,6.534635,6.014719,2.07,52554.41103
135,74411.05989,5.534628,7.210123,6.44,43537.50295
...,...,...,...,...,...
3774,67079.97604,5.767122,6.952633,2.26,33434.09618
4404,46135.24786,5.656343,7.303475,3.47,39232.22491
2307,71713.79826,6.446438,7.845240,6.15,26861.13336
408,80836.34486,5.767367,7.421921,3.02,49864.46977
170,67009.81567,6.849770,7.610721,3.22,39737.12261

In [21]:
y_test

471     1.399663e+06
2517    3.989095e+05
23      7.439998e+05
3918    1.312467e+06
135     1.393747e+06
            ...
3774    1.204214e+06
4404    6.151449e+05
2307    1.361829e+06
408     1.811377e+06
170     1.528756e+06
Name: Price, Length: 910, dtype: float64

In [22]:
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

In [23]:
print("Mean Absolute Error:", mae)
print("Mean Squared Error:", mse)
print("R² Score:", r2)

Mean Absolute Error: 82598.89895520086
Mean Squared Error: 10450595737.12179
R² Score: 0.9086390843030994

In [24]:
pickle.dump(lr, open("model.pkl", "wb"))